### ISSUE TITLE
File selection for multiple files

### ISSUE THREAD

**Issue by Cateye82** [garystubbings/nativescript-simple-filepicker#1]
ERROR Error: Uncaught (in promise): Error: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getAuthority()' on a null object reference
JS: (file:///node_modules/nativescript-simple-filepicker/simple-filepicker.js:52:0)
JS:     at push.../node_modules/@nativescript/angular/zone-js/dist/zone-nativescript.js.ZoneDelegate.invoke(file:///node_modules/@nativescript/angular/zone-js/dist/zone-nativescript.js:388:0)
JS:     at onInvoke(file:///node_modules/@angular/core/fesm5/core.js:26256:0)
JS:     at push.../node_modules/@nativescript/angular/zone-js/dist/zone-nativescript.js.ZoneDelegate.invoke(file:///node_modules/@nativescript/angular/zone-js/dist/zone-nativescript.js:387:0)
JS:     at push.../node_modules/@nativescript/angular/zone-js/dist/zone-nativescript.js.Zone.run(file:///node_modules/@nativescript/angular/zone-js/dist/zone-nativescript.js:138:0)
JS:     at (file:///node_modules/@nativescript/angular/zone-js/dist/zone-nativescript.js:883:0)
JS:     at push.../node_modules/@nativescript/angular/zone-js/dist/zone-nativescript.js.Zone...

Happens when you try so select more then one file with Nativescript 6.2 and a Google Pixel 3 XL.
Would be great if we could find a solution to solve this, as it is a great plugin! Thank you.

**Comment by Cateye82** [comment]
I found a solution. For Android you have to replace the simple-filepicker.android.js inside the node_modules/nativescript-simple-filepicker folder with the following one. 
```

"use strict";
Object.defineProperty(exports, "__esModule", {value: true});
var app = require("tns-core-modules/application");
var permissions = require("nativescript-perms");

function callIntent(context, intent, pickerType) {
    return permissions.request('storage').then(function () {
        return new Promise(function (resolve, reject) {
            var onEvent = function (e) {
                console.log(' startActivityForResult ', e.requestCode);
                if (e.requestCode === pickerType) {
                    resolve(e);
                    app.android.off(app.AndroidApplication.activityResultEvent, onEvent);
                }
            };
            app.android.once(app.AndroidApplication.activityResultEvent, onEvent);
            context.startActivityForResult(intent, pickerType);
        });
    });
}

exports.openFilePicker = function (params) {
    var extensions;
    if (params && params.extensions && params.extensions.length > 0) {
        extensions = Array.create(java.lang.String, params.extensions.length);
        for (var i = 0; i < params.extensions.length; i++) {
            extensions[i] = params.extensions[i];
        }
    }
    var context = app.android.foregroundActivity || app.android.startActivity;
    var FILE_CODE = 1231;
    var intent = new android.content.Intent(android.content.Intent.ACTION_GET_CONTENT);
    intent.setType(extensions && extensions.join(' | ') || '*/*');
    intent.addCategory(android.content.Intent.CATEGORY_OPENABLE);
    intent.setAction(android.content.Intent.ACTION_OPEN_DOCUMENT);
    intent.putExtra(android.content.Intent.EXTRA_ALLOW_MULTIPLE, params && !!params.multipleSelection || false);
    return callIntent(context, intent, FILE_CODE).then(function (result) {

        if (result.resultCode === android.app.Activity.RESULT_OK) {
            if (result.intent != null) {
                var uri = result.intent.getData();
                var bundle = result.intent.getClipData();

                if (uri) {
                    return {
                        files: [com.nativescript.simple.FilePicker.getPath(context, uri)]
                    };
                }

                if (bundle) {
                    var tmpFiles = [];
                    for (var i = 0; i < bundle.getItemCount(); i++) {
                        let fileUri = bundle.getItemAt(i).getUri();
                        tmpFiles.push(com.nativescript.simple.FilePicker.getPath(context, fileUri));
                    };

                    return {
                        files: tmpFiles
                    };
                }
            }
            return {
                files: []
            };
        } else {
            throw new Error('no_file');
        }
    });
};
//# sourceMappingURL=simple-filepicker.android.js.map

```
